### ISSUE TITLE
It breaks Pods on WPEngine environment with multisite

### ISSUE THREAD

**Issue by 2aces** [pods-framework/pods-alternative-cache#11]
## Issue Explanation

Don't know exactly how to classify this -- if it's a bug or something too much specific to our setup --, but since last update, I was unable to create and update pods. As soon as we disabled alternative cache plugin, things gone back to normal.

We tried to create new pods in a fresh site, but they would not appear. But when we tried to create again, the system gave a "Pod already exists" message. 

When exporting/importing packages ( and when cloning websites with WPMUDEV clone plugin) the pods appeared on pods list and anywhere they were queried, but not on menu, and we could not access custom post type items list (edit.php). And they could not be updated

Even after hitting clear cache on Pod Settings and WPE cache, nothing worked. But with alternative cache disabled, worked as supposed.

Hope it helps.

### Debug Information

- WordPress Version: 4.5.3
- PHP Version: 5.5.9-1ubuntu4.17
- MySQL Version: 5.6.29
- Server Software: Apache
- Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
- Session Save Path: /var/lib/php5
- Session Save Path Exists: Yes
- Session Save Path Writeable: Yes
- Session Max Lifetime: 1440

### Opcode Cache:

- Apc: No
- Memcached: No
- Redis: No

### Object Cache:

- Apc: No
- Apcu: No
- Memcache: Yes
- Memcached: Yes
- Redis: Yes

- WP Multisite Mode: Yes
- WP Memory Limit: 64M
- Pods Network-Wide Activated: No
- Pods Install Location: /nas/content/staging/superlumina/wp-content/plugins/pods/
- Pods Tableless Mode Activated: No
- Pods Light Mode Activated: No
- Currently Active Theme: Atmosphere Pro

### Currently Active Plugins:

- Adminimize: 1.10.5
- AMP: 0.3.2
- Autoptimize: 2.0.2
- BJ Lazy Load: 1.0.6
- Bulk Images to Posts: 3.6.6
- Cloner: 1.7.2
- Force Regenerate Thumbnails: 2.0.5
- Genesis eNews Extended: 2.0.2
- Genesis Grid: 1.4.2
- Genesis Simple Edits: 2.1.4
- Genesis Taxonomy Images: 1.1.1
- Genesis Translations: 2.2.0
- Glue for Yoast SEO & AMP: 0.3.2
- Google Analytics by MonsterInsights: 5.5.2
- Gravity Forms: 1.9.12.16
- Gravity Forms MailChimp Add-On: 3.6.4
- Intuitive Custom Post Order: 3.0.7
- Material Admin Theme: 1.3.4
- Media Library Assistant: 2.31
- Pods - Custom Content Types and Fields: 2.6.6
- Pods SEO: 2.0
- Remove Dashboard Access: 1.1.3
- Save & Import Image from URL: 0.5
- Save with keyboard: 2.1
- Seamless Sticky Custom Post Types: 1.4
- Simple Social Icons: 1.0.13
- Sunny (Connecting CloudFlare and WordPress): 1.5.4
- superlumina» Subsites: 0.5.0wip
- Support System: 2.1.9.1
- Tiled Galleries Carousel Without Jetpack: 2.1
- Ultimate Branding: 1.8.2
- Ultimate Facebook: 2.8.2
- User Role Editor: 4.25.2
- WordPress Importer: 0.6.1
- WordPress MU Domain Mapping: 0.5.5.1
- WP-InstantArticles: 1.0.0
- WPMU DEV Dashboard: 4.1.0
- Yoast SEO: 3.3.4

**Comment by sc0ttkclark** [comment]
Thanks for the info! I'm also looking into a similar issue in another case, will update this once I know what the solution can be.

**Comment by 2aces** [comment]
So far, i just turned it off, as it isn't really impacting on performance. Glad to know this "heads up" may benefit others.

PS: Thanks for the fantastic work with pods, guys.

**Comment by sc0ttkclark** [comment]
Please test with the latest version of Pods Alt Cache 2.0.1, let me know if that resolves your issues.

**Comment by 2aces** [comment]
@sc0ttkclark I guess so, but not sure. 

It worked perfectly on staging and when on production, the settings changed on pods (e.g. is hierarchical on custom taxonomies) are kept but now, when cloning a website using WPMUDEV cloner plugin, I have to export / import packages between sites and previously the new website already had the pods copied from the site it was cloned from, no need to export/import packages.

Don't know if this is the expected behavior, bug in WPMUDEV plugin of if PAC is still buggy. So, i won't close this issue. (but thanks for solving the most critic aspect of the problem!)

**Comment by sc0ttkclark** [comment]
If you copy the /wp-content/podscache/ folder from site to site, that can happen. You'll want to clear your Pods cache or delete that folder.

**Comment by Ramoonus** [comment]
should /podscache/ be cleaned on activation of the plugin?

**Comment by sc0ttkclark** [comment]
Probably a good idea, also good idea to delete on deactivation too.

**Comment by 2aces** [comment]
@sc0ttkclark Thanks for the help and bugfix. Sorry for not giving feedback sooner.
