### ISSUE TITLE
WP-CLI triggers PHP Notice Use of undefined constant FS_CHMOD_DIR - assumed 'FS_CHMOD_DIR'

### ISSUE THREAD

**Issue by lkraav** [pods-framework/pods-alternative-cache#13]
When running `wp-cli` commands, every so often I get `PHP Notice:  Use of undefined constant FS_CHMOD_DIR - assumed 'FS_CHMOD_DIR' in /home/warmpress/wp-content/plugins/pods-alternative-cache/classes/Pods/Alternative/Cache/File.php on line 382`

Everything is at latest version.

**Comment by sc0ttkclark** [comment]
Fixed in latest version on GitHub, thanks for the heads up!
