### ISSUE TITLE
Update Assets for New Branding for Pods

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-alternative-cache#14]
@sc0ttkclark do we want to add WPEngine logo to this one or is this one particularly for WPEngine or multiple hosts?

**Comment by sc0ttkclark** [comment]
Probably not, it was built for WPEngine but it's super useful everywhere. I run it on all my sites just for speed.

**Comment by jimtrue** [comment]
ah, then just use the Assets from the new pods branch? Unless we wanna say 'cache!' or something in the banner or maybe a fast moving pod logo

**Comment by sc0ttkclark** [comment]
That sounds about right (slightly different logo)

**Comment by jimtrue** [comment]
Fixed #15
