### ISSUE TITLE
Stale data when activated using the LocalWP dev environment

### ISSUE THREAD

**Issue by dingman** [pods-framework/pods-alternative-cache#24]
I had this plugin installed and activated in my LocalWP environment, and it was showing stale data. Using the built-in Pods Clear Cache button did not purge any data. Upon deactivating the plugin, all data showed readily and successfully.

In my particular case, I had "Settings" pages that I would create, then could not be deleted, showing "Pod not found" and likewise, new ones created would not show up.

I don't have any other details beyond that, simply that it wasn't working for me, unfortunately.

`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\Users\Jonathan\Local Sites\local-\app\public
wordpress_size: loading...
uploads_path: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content/uploads
uploads_size: loading...
themes_path: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content/themes
themes_size: loading...
plugins_path: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name:  (v-fresh)
version: undefined
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo, custom-header, widgets
theme_path: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content/themes/v-fresh

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.4, author: the WordPress team

### wp-plugins-active (11) ###

Admin Menu Editor: version: 1.9.5, author: Janis Elsts
Bulk Block Converter: version: 1.0.1, author: Organic Themes
Compress JPEG & PNG images: version: 3.2.1, author: TinyPNG
Image Regenerate & Select Crop: version: 5.4.3, author: Iulia Cazan
Pods - Custom Content Types and Fields: version: 2.7.21, author: Pods Framework Team
Query Monitor: version: 3.6.0, author: John Blackbourn
UpdraftPlus - Backup/Restore: version: 2.16.27.24, author: UpdraftPlus.Com, DavidAnderson
WP All Import - Yoast WordPress SEO Add-On: version: 1.1.8, author: Soflyy
WP All Import Pro: version: 4.6.2, author: Soflyy
WP Search with Algolia: version: 1.3.0, author: WebDevStudios
Yoast SEO: version: 14.6.1, author: Team Yoast

### wp-plugins-inactive (7) ###

Better Admin Bar: version: 2.4, author: KubiQ
Branda: version: 3.3.1, author: WPMU DEV
Duplicate Page: version: 4.2, author: mndpsingh287
Pods Advanced Permalinks Add-On: version: 0.1, author: Pods Framework Team
Pods Alternative Cache: version: 2.1.0, author: Pods Framework Team
Pods SEO: version: 2.2, author: Pods Framework Team
WP-Optimize - Clean, Compress, Cache: version: 3.1.2, author: David Anderson, Ruhani Rabin, Team Updraft

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1799
imagemagick_version: ImageMagick 7.0.7-11 Q16 x64 2017-11-23 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 16 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 1536
	imagick::RESOURCETYPE_MAP: 16 GB
	imagick::RESOURCETYPE_MEMORY: 8 GB
	imagick::RESOURCETYPE_THREAD: 6
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: nginx/1.16.0
php_version: 7.4.1 64bit
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_size: 300M
php_post_max_size: 1000M
curl_version: 7.67.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 7.4.1

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content
WP_PLUGIN_DIR: C:\Users\Jonathan\Local Sites\local-\app\public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.16.0
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 17.478M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: C:\Users\Jonathan\Local Sites\local-\app\public\wp-content\plugins\pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

**Comment by sc0ttkclark** [comment]
I haven't been able to reproduce this but I did fix an issue with cache clearing in PHP 8+, try checking again with Pods Alt Cache 2.1.2
